### ISSUE TITLE
Rerunning pipeline with Arks

### ISSUE THREAD

**Issue by charlesfeigin** [bcgsc/LongStitch#21]
Hi, I have a previously-generated set of scaffolds using the default longstitch run (tigment/ntlink) pipeline. I'm interested in running the extended pipeline with arks, and was wondering whether longstitch is able to resume a previous run. I.e., if I run the program in tigmint-ntLink-arks mode the same directory with the previous run, will it start from the beginning or pick up after ntlink? Thanks!

**Comment by lcoombe** [comment]
Hi @charlesfeigin,

Yes, if you just launch the command with the `tigmint-ntLink-arks` target specified in the same directory that you ran Tigmint-ntLink, then it will detect that the first two steps have already been completed and start at running `arks`, since the driver script is a makefile. 
To double check that this will happen, I often suggest doing a 'dry-run' - which you can do by adding `-n` to your command. This will print out the commands that will be run without actually running them. That would just allow you the sanity check that the pipeline will start off where you want it to.

Hope that helps!
Lauren

**Comment by charlesfeigin** [comment]
Thanks so much!
