### ISSUE TITLE
Specifying -a parameter for ARCS through LongStitch

### ISSUE THREAD

**Issue by aakashsur** [bcgsc/LongStitch#37]
Here's my command 

```
longstitch tigmint-ntLink-arks \
    draft=assembly \
    reads=reads \
    t=40 \
    G=800000000 \
    span=2 \
    a=0.5
```

But I get the following error -

```
indexlr v1.4: Using more than 5 threads does not scale, reverting to 5.
usage: ntlink_pair.py [-h] -s S -m M [-p P] [-n N] -k K [-z Z] [-a A] [-f F]
                      [-x X] [-v] [--verbose]
                      FILES [FILES ...]
ntlink_pair.py: error: argument -a: invalid int value: '0.5'
make[1]: *** [/sw/contrib/stf-src/ntlink/1.1.1/ntLink:156: test_23.cut250.tigmint.fa.k32.w100.z1000.n2.scaffold.dot] Error 2
make[1]: Leaving directory '/mmfs1/gscratch/scrubbed/asur/assemblies/egracilis/masurca_corrected_matepair/test_23'
make: *** [/sw/contrib/stf-src/longstitch/1.0.1/longstitch:165: test_23.cut250.tigmint.fa.k32.w100.z1000.stitch.abyss-scaffold.fa] Error 2
```

Presumably because both `ntlink` and `arcs` have the `-a` flag?

**Comment by lcoombe** [comment]
Hi @aakashsur,

Thanks for pointing this out. I suppose that on our end, we usually don't tweak the `a` parameter, so we haven't come across this yet.

As you mentioned, it's due to the collision between `a` parameters in ntLink and ARKS-long. To fix that, I added a new `a_ntLink` parameter to the `longstitch` Makefile, so that the `a` value intended for ARKS-long doesn't get passed to ntLink. That `a` parameter in ntLink isn't a parameter that we really document anyway for LongStitch, nor one that I recommend changing, so it shouldn't be an issue for users.

I added that change in #38 - Could you try using the current master branch and see if that fixes the issue for you?

Thanks for your interest in LongStitch!
Lauren

**Comment by aakashsur** [comment]
Great, seems to work!
