### ISSUE TITLE
Support for HIFI data

### ISSUE THREAD

**Issue by alexvasilikop** [bcgsc/LongStitch#71]
Hello,

Is there a plan to incorporate HIFI long reads in the pipeline. I have used tigmint separately to identify breakpoints using the option: 
```
longmap=hifi
```

However, when I used tigmint within longstitch there is no such option and the reads are mapped as ONT data. The result shows that there are significantly more breakpoints identified by longstitch (#Attempted corrections: 691) in comparison to tigmint with the otiopn for HiFi reads (#Attempted corrections: 218). I am not sure though that is is due to the issue of how the reads are treated.

Thanks
Alex

**Comment by warrenlr** [comment]
great suggestion, thank you for reaching out to us. I will make sure to pass this on to our developers when they return from vacation.  Thank you for your interest in tigmint and longstitch,
Rene

**Comment by lcoombe** [comment]
Hi @alexvasilikop,

Since LongStitch and it's main constituent steps (Tigmint-long, ntLink, arcs-long) are powered by makefiles, any parameter setting that you supply to LongStitch will be passed to Tigmint. So, if you include `longmap=hifi` in your LongStitch command, it will currently pass that on to Tigmint, and map using that preset with minimap2.

But thank you for bringing this up, because I agree it is more clear to have that parameter listed in the LongStitch help page so it's more obvious for users. I'll make that change in an upcoming release!

Lauren

**Comment by lcoombe** [comment]
Hi @alexvasilikop,

I documented the `longmap` parameter in the `longstitch` help page and README in #72 - the changes will be in a new release v1.0.5 shortly.

Thanks!
Lauren
