### ISSUE TITLE
Conda installation is non-functional

### ISSUE THREAD

**Issue by drdna** [bcgsc/LongStitch#80]
Environment is non-solvable

**Comment by lcoombe** [comment]
Hi @drdna,

Without more information about your environment, command, error, etc., here are some of the tips I generally give to users when they have conda install issues:
1. Try installing longstitch in a fresh conda environment. Sometimes, if you get errors that there are conflicts in versions, it is due to existing tools installed, and will be solved with a new environment.
2. If conda is taking a very long time, `mamba` is a good alternative
```
conda create -n longstitch_env
conda activate longstitch_env
conda install  -c bioconda -c conda-forge python=3.9 mamba
mamba install -c bioconda -c conda-forge longstitch
```

Feel free to update with more information (command, environment info, error log) if those tips do not solve the issue for you.

Thank you for your interest in LongStitch!
Lauren
